correcting the wrong Class name to right Class Name
IamMU/Fancy-Print pull request #15
Opened 2022-10-11 16:51 UTC by achiverram28

2022-10-11 18:52 UTC, achiverram28 commented
I have added the required function called as convert_tags_to_color in printer.py , and made some necessary required changes , please check the pr and give it a hacktober-fest accepted tag

2022-10-11 20:10 UTC, IamMU requested changes
Epic job @achiverram28 :fire: 
See the comments/with the requested change(very minimal - have code_of_conduct on the works currently :wink: )

2022-10-11 20:10 UTC, IamMU commented on README.md
>  ```
Nice catch :+1:

2022-10-11 20:10 UTC, IamMU commented on fancyprint/printer.py
> +    def log(self, message: str, log_config = LogConfig()):
Add 2 spaces between function end and new function

2022-10-11 22:03 UTC, achiverram28 commented
I have added the spaces

2022-10-12 11:10 UTC, IamMU reviewed
Epic work @achiverram28 :+1:

2022-10-12 11:11 UTC, merged

2022-10-12 11:14 UTC, IamMU commented
@achiverram28 you changed the file structure :|
Make another pr with the correct structure, i am marking this as invalid

2022-10-12 15:48 UTC, achiverram28 commented
I had changed a lot of files, and cannot make out what I have made, and src was not required , it was extra , and please comment what changes to make , but after working a lot on it and getting an invalid tag is jot worthy, please of possible remove it, it's a request,  it will affect my hacktoberfest .Please I guess you understand

2022-10-12 15:58 UTC, IamMU commented
@achiverram28 you're right, the pr doesn't deserve a invalid tag. Hacktoberfest doesn't have good rules and needs more explaining for maintainers. Don't worry, it will be removed once you add the src folder back. The project follow the latest standards(https://packaging.python.org/en/latest/tutorials/packaging-projects/) and the new structure. Please consider following the standard and making a new pr for that. :slightly_smiling_face: 
Don't worry about this pr being invalid, make another one and I'll accept it. You'll get 2 points then i guess. I'll have to ask in the discord server to be sure.
Please do the requested changes.